# Available substitution tags: ${PLAYER}, ${ENTITY}, ${ITEM}
message-for-awarding-head: '${PLAYER} was awarded the head of ${ENTITY} by feeding them'

# Note: The drop-chance uses the values of head-drop-rates.txt from the base plugin


# Note: either list formats works: one line [x,y,z] or multiple lines with -x -y -z
# Choose whichever you prefer, I've set some example defaults below

taming-triggers-head-drop-chance: [wolf, cat, parrot, horse, donkey, mule, llama, trader_llama]
feeding-to-tame-triggers-head-drop-chance: [wolf, cat, parrot, horse, donkey, mule, llama, trader_llama]
feeding-to-heal-triggers-head-drop-chance: [horse]
feeding-to-breed-triggers-head-drop-chance: 
  - wolf
  - cat
  - horse
  - donkey
  - llama
  - trader_llama
  - turtle

disable-head-drop-from-murder: [wolf, cat, parrot]