name: PeacefulPetHeads
main: net.evmodder.PeacefulPetHeads.PeacefulPetHeads
author: EvModder
description: Adds non-deadly means of obtaining pet heads.
website: https://dev.bukkit.org/projects/dropheads
version: 1.1
api-version: 1.13
depend: [DropHeads]